CREATE TABLE CANDIDATES  (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CANDIDATE_NAME VARCHAR(2550),
    CANDIDATE_MOBILE_NUMBER VARCHAR(2550),
    CANDIDATE_EMAIL VARCHAR(2550),
    CANDIDATE_SKILLS VARCHAR(2550),
    SPOC VARCHAR(2550),
    DELIVERY_LEAD VARCHAR(2550)
);

ALTER TABLE CANDIDATES DROP PRIMARY KEY;